name: Release Android App

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.27.3'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Upload App Bundle as Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
